// <auto-generated />
namespace QuoteWall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Reset2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reset2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806242058372_Reset2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
